<!-- index.html -->
<!DOCTYPE html>
<html>
<head>
    <title> Chat</title>
    <style>
        /* 简单的样式 */
        .container {
            width: 800px;
            margin: 0 auto;
        }
        #chat-box {
            height: 500px;
            border: 1px solid #ccc;
            padding: 10px;
            overflow-y: auto;
        }
        .message {
            margin: 5px 0;
            padding: 8px;
            border-radius: 5px;
        }
        .user-message {
            background-color: #e3f2fd;
            margin-left: 20%;
        }
        .bot-message {
            background-color: #f5f5f5;
            margin-right: 20%;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>AI Chat</h1>
        <div id="chat-box"></div>
        <div>
            <input type="text" id="user-input" style="width: 70%; padding: 10px;">
            <button onclick="sendMessage()" style="width: 25%; padding: 10px;">发送</button>
        </div>
    </div>

    <script>
        // 处理用户输入
        async function sendMessage() {
            const input = document.getElementById('user-input');
            const message = input.value.trim();
            if (!message) return;

            // 添加用户消息到聊天框
            addMessage('user', message);
            input.value = '';

            try {
                // 发送请求到后端
                const response = await fetch('/chat', {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({ message: message })
                });

                const data = await response.json();
                if (data.reply) {
                    addMessage('bot', data.reply);
                }
            } catch (error) {
                console.error('Error:', error);
                addMessage('bot', '出错了，请稍后再试');
            }
        }

        // 添加消息到聊天框
        function addMessage(role, content) {
            const chatBox = document.getElementById('chat-box');
            const messageDiv = document.createElement('div');
            messageDiv.className = `message ${role}-message`;
            messageDiv.textContent = content;
            chatBox.appendChild(messageDiv);
            chatBox.scrollTop = chatBox.scrollHeight;
        }
    </script>
</body>
</html>
